on: 
    release:
        types: [created]

permissions:
    contents: write
    packages: write

jobs:
    releases-matrix:
        name: Release Go Binary
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, darwin]
                goarch: ["arm64", amd64]
        steps:
        - name: Show environment
          run: export
        - uses: actions/checkout@v2
        - uses: wangyoucao577/go-release-action@v1.52
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: "https://dl.google.com/go/go1.23.0.linux-amd64.tar.gz"
            build_command: "make build"
            build_flags: "build"
            binary_name: "cscheck"
            extra_files: README.md cscheck scripts